In [2]:
class Man:
    def __init__(self,name):
        self.name = name
        print("Initialized!")

    def hello(self):
        print("Hello"+self.name+"!")

    def goodbye(self):
        print("Good-bye"+self.name+"!")

m=Man("David")
m.hello()
m.goodbye

Initialized!
HelloDavid!


<bound method Man.goodbye of <__main__.Man object at 0x000001C4D4C28C80>>

In [2]:
import numpy as np
x = np.array([1.0, 2.0, 3.0])
print(x)
type(x)

[1. 2. 3.]


numpy.ndarray

In [8]:
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 4.0, 6.0])
x+y
x-y
x*y
x*y
x/y
x = np.array([1.0, 2.0, 3.0])
x/2.0

array([0.5, 1. , 1.5])

In [10]:
A = np.array([[1,2],[3,4]])
print(A)

[[1 2]
 [3 4]]


In [11]:
A.shape

(2, 2)

In [12]:
A.dtype

dtype('int32')

In [13]:
B = np.array([[3,0],[0,6]])
A+B

array([[ 4,  2],
       [ 3, 10]])

In [14]:
A*B

array([[ 3,  0],
       [ 0, 24]])